animals = ['bear', 'python', 'peacock', 'kangaroo', 'whale', 'platypus']
bear = animals[0]
python = animals[1]
peacock = animals[2]
kangaroo = animals[3]
whale = animals[4]
platypus = animals[5]

print "The animal at 1 is", animals[1]
print "The 3rd animal is", animals[3 - 1]
print "The 1st animal is", animals[1 - 1]
print "The animal at 3 is", animals[3]
print "The 5th animal is", animals[5 - 1]
print "The animal at 2 is", animals[2]
print "The 6th animal is", animals[6 - 1]
print "The animal at 4 is", animals[4]
